version: '3'
services:
  rabbit:
    container_name: dev-rabbit
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"